server:
  port: 8083
  servlet.context-path: /auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    default-schema:
  datasource:
    url:

auth:
  jwt:
    secret: DF9D3B08F4D9F13B664F88160F416FCDAC15D0ABBEA410A15347D5E1DB5C21BCF0E116DF8BBD2ACD3CDB899D34D26111DC0F9D8FE3DBF09F908BB7D3A16C5878
    expiration: 7200000 # 2 Hours

security:
  signing-key: DF9D3B08F4D9F13B664F88160F416FCDAC15D0ABBEA410A15347D5E1DB5C21BCF0E116DF8BBD2ACD3CDB899D34D26111DC0F9D8FE3DBF09F908BB7D3A16C5878
  encoding-strength: 512
  security-realm: EHRouteRealm
  jwt:
    client-id: testjwtclientid
    client-secret: aadwad
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: resourceID
