server:
  port: 6001
  servlet.context-path: /identity

eureka:
  client:
    serviceUrl:
      defaultZone: https://ehroute-discovery-service.herokuapp.com/eureka/

spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  application:
    name: identity-service
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
    enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ehroute?schema=business&autoReconnect=true
    username: postgresql
    password: ${DB_PASSWORD}
    #pool:
      #enabled: true
      #initial-size: 10
      #max-size: 100

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework: Error
    org.springframework.data.r2dbc: Debug
