version: '3'

services:
  
  config:
    build:
      context: ./config-server
      dockerfile: dockerfile
    ports:
      - 8888:8888
    networks:
      - net
    mem_limit: 512MB
    hostname: config
    container_name: config
  
  discovery:
    build:
      context: ./discovery-service
      dockerfile: dockerfile
    ports:
      - 8761:8761
    networks:
      - net
    mem_limit: 512MB
    depends_on:
      - config
    hostname: discovery
    container_name: discovery
    command: ["./wait-for-it.sh","config:8888","--timeout=100","--","/usr/local/bin/start.sh"]

  gateway:
    build:
      context: ./gateway-service
      dockerfile: dockerfile
    ports:
      - 8080:8080
    networks:
      - net
    mem_limit: 512MB
    depends_on:
      - config
      - discovery
    hostname: gateway
    container_name: gateway
    command: ["./wait-for-it.sh","discovery:8761","--timeout=100","--","/usr/local/bin/start.sh"]
 
  auth:
    build:
      context: ./auth-service
      dockerfile: dockerfile
    ports:
      - 8083:8083
    networks:
      - net
    mem_limit: 512MB
    depends_on:
      - config
      - discovery
      - gateway
    hostname: auth
    container_name: auth
    command: ["./wait-for-it.sh","gateway:8080","--timeout=100","--","/usr/local/bin/start.sh"]

  patient:
    build:
      context: ./patient-service
      dockerfile: dockerfile
    ports:
      - 8082:8082
    networks:
      - net
    mem_limit: 512MB
    depends_on:
      - config
      - discovery
      - gateway
      - auth
    hostname: patient
    container_name: patient
    command: ["./wait-for-it.sh","gateway:8080","--timeout=100","--","/usr/local/bin/start.sh"]

  provider:
    build:
      context: ./provider-service
      dockerfile: dockerfile
    ports:
      - 8081:8081
    networks:
      - net
    mem_limit: 512MB
    depends_on:
      - config
      - discovery
      - gateway
      - auth
    hostname: provider
    container_name: provider
    command: ["./wait-for-it.sh","gateway:8080","--timeout=100","--","/usr/local/bin/start.sh"]

networks:
  net:
    driver: bridge