version: 2.1

parameters:

  # ---------------------------------------------------------------------------- #
  #                                    Trigger                                   #
  # ---------------------------------------------------------------------------- #
  # region

  # Branch that triggers builds
  trigger-branch: 
    default: production
    type: string

  # Used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # endregion

  # ---------------------------------------------------------------------------- #
  #                                   Services                                   #
  # ---------------------------------------------------------------------------- #
  # region

  config-server:
    type: boolean
    default: false

  discovery-service:
    type: boolean
    default: false

  gateway-service:
    type: boolean
    default: false

  account-service:
    type: boolean
    default: false

  auth-service:
    type: boolean
    default: false

  identity-service:
    type: boolean
    default: false

  patient-service:
    type: boolean
    default: false

  provider-service:
    type: boolean
    default: false

  # endregion

  # ---------------------------------------------------------------------------- #
  #                                  Deployment                                  #
  # ---------------------------------------------------------------------------- #
  # region

  deploy:
    type: boolean
    default: false

  #endregion

executors:
  jdk11:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

jobs:

  # ---------------------------------------------------------------------------- #
  #                                    Trigger                                   #
  # ---------------------------------------------------------------------------- #
  # region

  trigger-workflows:

    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          # This step is added to demonstrate the possibility to dynamically set the user token
          name: Set token
          command: echo "export CIRCLE_USER_TOKEN=${CIRCLECI_TOKEN}" >> $BASH_ENV
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/monorepo.sh && .circleci/monorepo.sh
          environment:
            # (optional) print additional debug information
            MONOREPO_DEBUG: "true"
            # (optional) additional CI parameters to include in the pipeline (must be a valid JSON)
            CI_PARAMETERS: '{ "deploy": true }'

  # endregion

  # ---------------------------------------------------------------------------- #
  #                                     Build                                    #
  # ---------------------------------------------------------------------------- #
  # region

  build:

    parameters:
      package_name:
        type: string

    executor: jdk11
    working_directory: ~/project/<< parameters.package_name >>

    environment:
      # Limit max heap to 512MB for Heroku's max memory limit on free apps
      JVM_OPTS: -Xmx512m
      TERM: dumb
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_PASSWORD: ${GIT_PASSWORD}

    steps:

      - checkout:
          path: ~/project

      - run: echo "Building << parameters.package_name >> ..."

      #  - persist_to_workspace:
      #    root: ~/project
      #    paths:
      #      - << parameters.package_name >>

      - setup_remote_docker:
          version: 19.03.13

      # Decrypt app properties
      # - run: openssl enc -d -aes-256-ecb -md md5 -in src/main/resources/application.yml.secrets -out src/main/resources/application.yml -k $DECRYPTION_KEY

      # Restore dependencies cache
      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline

      # Cache dependencies
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths: 
            - ~/.m2

      # Upload code coverage report
      - run: bash <(curl -s https://codecov.io/bash)

      # Analyze on SonarCloud
      - run: mvn verify sonar:sonar -Dsonar.projectKey=ehroute:<< parameters.package_name >> -Dsonar.login=${SONAR_TOKEN}

      # Package application
      - run: mvn clean install

      # Build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t muizzmahdy/ehroute-<< parameters.package_name >>:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push muizzmahdy/ehroute-<< parameters.package_name >>:$TAG

      #   # store raw contents of src code
      #  - store_artifacts:
      #    path: target/classes
      #    destination: config-server-artifacts

  # endregion

  # ---------------------------------------------------------------------------- #
  #                                    Deploy                                    #
  # ---------------------------------------------------------------------------- #
  # region

  deploy:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/project/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job.
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_name >> (<< pipeline.parameters.deploy >>) ..."

  # endregion

workflows:
  version: 2

  # ---------------------------------------------------------------------------- #
  #                                    Trigger                                   #
  # ---------------------------------------------------------------------------- #
  # region

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
  
  # endregion

  # ---------------------------------------------------------------------------- #
  #                                   Services                                   #
  # ---------------------------------------------------------------------------- #
  # region

  config-server:
    when: << pipeline.parameters.config-server >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: config-server
          name: config-server-build

  discovery-service:
    when: << pipeline.parameters.discovery-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: discovery-service
          name: discovery-service-build

  gateway-service:
    when: << pipeline.parameters.gateway-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: gateway-service
          name: gateway-service-build

  account-service:
    when: << pipeline.parameters.account-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: account-service
          name: account-service-build

  auth-service:
    when: << pipeline.parameters.auth-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: auth-service
          name: auth-service-build

  identity-service:
    when: << pipeline.parameters.identity-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: identity-service
          name: identity-service-build

  patient-service:
    when: << pipeline.parameters.patient-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: patient-service
          name: patient-service-build

  provider-service:
    when: << pipeline.parameters.provider-service >>
    jobs:
      - build:
          filters:
            branches:
              only: << pipeline.parameters.trigger-branch >>
          package_name: provider-service
          name: provider-service-build
    # - deploy:
    #     package_name: provider-service
    #     name: provider-service-deploy
    #     requires:
    #       - provider-service-build

  # endregion
