server:
  port: 8081
  servlet.context-path: /provider

eureka:
  client:
    serviceUrl:
      defaultZone: https://ehroute-discovery-service.herokuapp.com/eureka/

spring:
  application:
    name: provider-service
