server:
  port: 8083
  servlet.context-path: /account

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: account-service
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
