server:
  port: 8082
  servlet.context-path: /patient

eureka:
  client:
    serviceUrl:
      defaultZone: https://ehroute-discovery-service.herokuapp.com/eureka/

spring:
  application:
    name: patient-service
