/*
 * This file is generated by jOOQ.
 */
package ehroute.identityservice.entities.db;


import ehroute.identityservice.entities.db.tables.AccountRoles;
import ehroute.identityservice.entities.db.tables.Accounts;
import ehroute.identityservice.entities.db.tables.Roles;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account_roles</code>.
     */
    public final AccountRoles ACCOUNT_ROLES = AccountRoles.ACCOUNT_ROLES;

    /**
     * The table <code>public.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccountRoles.ACCOUNT_ROLES,
            Accounts.ACCOUNTS,
            Roles.ROLES
        );
    }
}
