/*
 * This file is generated by jOOQ.
 */
package ehroute.identityservice.entities.db;


import ehroute.identityservice.entities.db.tables.AccountRoles;
import ehroute.identityservice.entities.db.tables.Accounts;
import ehroute.identityservice.entities.db.tables.Roles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account_roles</code>.
     */
    public static final AccountRoles ACCOUNT_ROLES = AccountRoles.ACCOUNT_ROLES;

    /**
     * The table <code>public.accounts</code>.
     */
    public static final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;
}
